### ISSUE TITLE
RTL Feature

### ISSUE THREAD

**Issue by mehrabcz** [SaeedRz96/django-unfold-admin#1]
Hi 
first of all thank you for forking unfold repository
i am very happy that Persian community is growing 

i did review the code and i didn't manage to see rtl.css or something like that to enable the rtl in settings to handle multi language
Could you please Guide me how to enable the rtl or disable it ?

**Comment by SaeedRz96** [comment]
Hello and thanks for your support
This repo just changed `unfold/static/unfold/css/styles.css` and `unfold/templates/admin/*.html` files of the forked project to be Rtl version as default you install it.
