### ISSUE TITLE
 error: Invalid filter: 'length_is'

### ISSUE THREAD

**Issue by AliDvlpr** [SaeedRz96/django-unfold-admin#2]
in the change page for models i got an error that shows this in browser:

![Screenshot 2024-08-09 225422](https://github.com/user-attachments/assets/c2756c44-59dd-4fd8-9c55-26df9187024c)

**Comment by SaeedRz96** [comment]
The `length_is` filter in this repository template has been removed from Django 5.1 and needs updates to fix this issue. Consider using Django < 5.1 to resolve the problem.

**Comment by AliDvlpr** [comment]
thanks 🙏
